"""Compile-time host contract for mixins; no runtime implementation lives here."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Any, NoReturn, Protocol

    from ast2python.emission.metadata import ScriptMetadata
    from ast2python.emission.python import _Writer
    from ast2python.lowering.model import IRNode, LoweringPlan
    from ast2python.lowering.target import TargetManifest, TargetValueBinding

    class EmissionContext(Protocol):
        plan: LoweringPlan
        target: TargetManifest
        writer: _Writer
        exact_pinelib: bool
        metadata: ScriptMetadata | None
        current_function: str | None
        scope_parents: dict[str, str | None]
        local_names: dict[tuple[str, str], str]
        lexical_names: dict[str, tuple[str, str]]
        series_ids: dict[tuple[str, str], str]
        scalar_declarations: dict[str, tuple[str, str, str]]
        names_by_source: dict[str, str]
        functions_by_name: dict[str, str]
        function_ir_ids: set[str]
        source_to_ir: dict[str, str]
        declarations_by_py: dict[str, tuple[str, str]]
        function_declarations: dict[str, str]
        nominal_types: dict[str, str]
        nominal_declarations: dict[str, str]
        nominal_registry: dict[str, Any] | None
        callable_declarations: dict[str, str]
        callable_names: dict[str, str]
        method_receivers: dict[str, tuple[str, str]]
        assignment_results: dict[str, str]
        request_methods: dict[str, tuple[str, str, list[str], str, bool, str]]
        direct_imports: dict[tuple[str, str], str]
        direct_call_aliases: dict[tuple[str, str, str], str]
        direct_value_aliases: dict[str, str]
        direct_operation_aliases: dict[str, str]

        def _prepare_names(self) -> None: ...

        def _scope(self, key: str) -> str: ...

        def _lookup_local(self, scope: str | None, name: str) -> str | None: ...

        @staticmethod
        def _stored_type(dtype: str) -> bool: ...

        def _binding_helper(self, dtype: str, operation: str) -> str: ...

        def _require_language_contract(self, capability: str) -> None: ...

        def _type_ref_text(self, key: str) -> str: ...

        def _declaration_type(self, key: str) -> str: ...

        def _series_argument(self, sid: str) -> str: ...

        def _history_policy(self, sid: str) -> str: ...

        def _series_identity(self, key: str) -> str | None: ...

        def _condition(self, key: str) -> str: ...

        def _default_block_value(self, key: str) -> str: ...

        def _value_block(self, key: str) -> None: ...

        def _block_expression(self, key: str) -> str: ...

        def _emit_if_chain(
            self,
            arms: list[tuple[str, str]],
            otherwise: str | None,
            *,
            value: bool,
            selector: str | None = None,
        ) -> None: ...

        def _capture_nonlocals(self, key: str) -> None: ...

        def _loop_expression(self, key: str) -> str: ...

        def _emit_loop(self, key: str, *, result: str | None = None) -> None: ...

        def _emit_result_block(self, key: str, result: str) -> None: ...

        def _emit_result_arms(
            self,
            arms: list[tuple[str, str]],
            other: str | None,
            result: str,
            key: str,
            selector: str | None = None,
        ) -> None: ...

        def _prepare_nominal_types(self) -> None: ...

        def _varip_nominal_array_supported(self, dtype: str) -> bool: ...

        def _runtime_type(self, dtype: str) -> str: ...

        def _nominal_member(self, key: str) -> str | None: ...

        def _nominal_call(
            self, key: str, call: dict[str, Any], rendered: dict[str, str]
        ) -> str: ...

        def _nominal_assignment(self, key: str, target: str, value: str) -> bool: ...

        def _assignment_value(self, key: str) -> str: ...

        def _prepare_requests(self) -> None: ...

        def _request_error(self, key: str, message: str) -> NoReturn: ...

        def _request_shape(self, key: str) -> str: ...

        def _request_expression_argument(self, key: str) -> str: ...

        def _emit_request_methods(self) -> None: ...

        def _node(self, ir_id: str) -> IRNode: ...

        def _attrs(self, ir_id: str) -> dict[str, Any]: ...

        def _fields(self, ir_id: str) -> dict[str, Any]: ...

        def _roles(self, ir_id: str) -> dict[str, tuple[str, ...]]: ...

        def _role(self, ir_id: str, role: str) -> tuple[str, ...]: ...

        def _safe(self, value: str, prefix: str, identity: str) -> str: ...

        def _prepare_legacy_names(self) -> None: ...

        def _legacy_lookup(self, scope: str | None, name: str) -> str | None: ...

        def _legacy_series_identity(self, ir_id: str) -> str | None: ...

        def _prepare_direct_imports(self) -> None: ...

        def _subtree(self, ir_id: str) -> tuple[str, ...]: ...

        def _runtime_operation(self, opcode: str, *arguments: str) -> str: ...

        def _value(self, ir_id: str, binding: TargetValueBinding) -> str: ...

        def _identifier(self, ir_id: str) -> str: ...

        def _call(self, ir_id: str) -> str: ...

        def _switch_expression(self, ir_id: str) -> str: ...

        def _expr(self, ir_id: str) -> str: ...

        def _emit_block(self, block_ir: str, *, return_last: bool = False) -> None: ...

        def _emit_statement(self, ir_id: str) -> None: ...

        def _emit_function(self, ir_id: str) -> None: ...

        def emit(self) -> str: ...
