"""Shared overload selection through compilation, state and source-bound imports.

Expected values are hand-derived from these bodies, not generated by the runtime.
"""

import json

import pytest
from pinelib import CallbackFrame, is_na
from pinelib.state.checkpoint import from_portable

from tests.test_locked_library_execution import (
    advance,
    compile_linked,
    library,
    runtime_for,
    script,
)
from tests.test_user_function_overload_execution import compile_family, compile_plain


@pytest.mark.parametrize("version", [5, 6])
@pytest.mark.parametrize("imported", [False, True])
@pytest.mark.parametrize(
    "fn,method,body,expected",
    [
        (
            "export f(string x)=>str.length(x)",
            "export method f(int self)=>self+1",
            'plot(NSf(2))\nplot(NSf("abcd"))',
            [3, 4],
        ),
        (
            "export f(float x)=>x+0.5",
            "export method f(int self)=>self+1",
            "plot(NSf(2))\nplot(NSf(2.0))",
            [3, 2.5],
        ),
        (
            "export f(int x,int y)=>x+y",
            "export method f(int self)=>self+1",
            "plot(NSf(2))\nplot(NSf(2,3))",
            [3, 5],
        ),
        (
            "export f(string x,int n=2)=>str.length(x)+n",
            "export method f(int self,int n=1)=>self+n",
            'plot(NSf(n=3,self=2))\nplot(NSf(x="abc"))',
            [5, 5],
        ),
        (
            "export f(bool x)=>not x",
            "export method f(array<int> self)=>self.size()",
            "plot(NSf(array.new<int>(2)))\nplot(NSf(true) ? 1 : 0)",
            [2, 0],
        ),
        (
            "export f(bool x)=>not x",
            'export method f(map<string,int> self)=>self.get("k")',
            'a=map.new<string,int>()\na.put("k",7)\nplot(NSf(a))\nplot(NSf(false) ? 1 : 0)',
            [7, 1],
        ),
        (
            "export f(bool x)=>not x",
            "export method f(matrix<float> self)=>self.get(0,0)",
            "a=matrix.new<float>(1,1,7.5)\nplot(NSf(a))\nplot(NSf(false) ? 1 : 0)",
            [7.5, 1],
        ),
        (
            "export f(float x)=>[x,x+0.5]",
            "export method f(int self)=>[self,self+1]",
            "[a,b]=NSf(2)\n[c,d]=NSf(2.0)\nplot(a+b+c+d)",
            [9.5],
        ),
    ],
)
def test_local_and_library_mixed_values(version, imported, fn, method, body, expected):
    c = compile_family(
        fn + "\n" + method, body.replace("NS", "lib." if imported else ""), version, imported
    )
    rt, cls = runtime_for(c)
    assert advance(rt, cls, [1, 2, 3]) == expected * 3
    assert (
        "mixed_user_callable_families_v1" not in c.plan.required_capabilities
    )  # compiler contract, no new runtime


@pytest.mark.parametrize("version", [5, 6])
@pytest.mark.parametrize("imported", [False, True])
def test_written_calls_loop_reuse_and_checkpoint_are_independent(version, imported):
    ns = "lib." if imported else ""
    declarations = "export count(float step)=>\n    var float n=0.0\n    n+=step\n    n\nexport method count(int step)=>\n    var int n=0\n    n+=step\n    n"
    body = f"plot({ns}count(1))\nplot({ns}count(10.0))\ns=0\nfor i=0 to 2\n    s:={ns}count(1)\nplot(s)"
    c = compile_family(declarations, body, version, imported)
    rt, cls = runtime_for(c)
    assert advance(rt, cls, [1, 2, 3]) == [1, 10.0, 3, 2, 20.0, 6, 3, 30.0, 9]
    for cut in (1, 2):
        part, _ = runtime_for(c)
        advance(part, cls, [1, 2, 3][:cut])
        saved = json.loads(json.dumps(part.checkpoint().to_dict()))
        restored, _ = runtime_for(c)
        restored.restore(saved)
        advance(restored, cls, [1, 2, 3][cut:], start=cut)
        assert restored.checkpoint().to_dict() == rt.checkpoint().to_dict()


@pytest.mark.parametrize("version", [5, 6])
@pytest.mark.parametrize("imported", [False, True])
def test_udt_reference_return_dot_and_function_forms_keep_field_rollback(version, imported):
    ns = "lib." if imported else ""
    decl = "export type C\n    int bars=0\n    varip int ticks=0\nexport f(int self)=>self+1\nexport method f(C self,int n)=>\n    self.bars+=n\n    self.ticks+=n\n    self"
    body = f"var {ns}C a={ns}C.new()\nvar {ns}C b={ns}C.new()\n{ns}f(a,1)\nb.f(n=10)\nplot(a.bars+b.bars)\nplot(a.ticks+b.ticks)\nplot({ns}f(2))"
    c = compile_family(decl, body, version, imported)
    rt, cls = runtime_for(c)
    assert advance(rt, cls, [1]) == [11, 11, 3]

    def tick(session, n, final):
        tx = session.begin(
            CallbackFrame("REALTIME_TICK", n, bar_index=1, realtime=True, final_tick=final)
        )
        cls(tx).run()
        values = [from_portable(e.payload["series"]) for e in session.visuals.working[-3:]]
        tx.commit()
        return values

    assert tick(rt, 1, False) == [22, 22, 3]
    clone, _ = runtime_for(c)
    clone.restore(json.loads(json.dumps(rt.checkpoint().to_dict())))
    for session in (rt, clone):
        assert tick(session, 2, False) == [22, 33, 3]
        assert tick(session, 3, True) == [22, 44, 3]
    assert rt.checkpoint().to_dict() == clone.checkpoint().to_dict()


@pytest.mark.parametrize("version", [5, 6])
def test_method_parameter_inference_uses_explicit_binding_not_receiver_position(version):
    c = compile_plain(
        'f(string x)=>str.length(x)\nmethod f(int self, other)=>other\nplot(f(1,2.5))\nplot(f("abc"))',
        version,
    )
    rt, cls = runtime_for(c)
    assert advance(rt, cls, [1, 2]) == [2.5, 3] * 2


@pytest.mark.parametrize("version", [5, 6])
@pytest.mark.parametrize("private_kind", ["function", "method"])
def test_private_more_specific_candidate_does_not_capture_export(version, private_kind):
    method = "method " if private_kind == "method" else ""
    other = "method " if private_kind == "function" else ""
    decl = f"{method}f(int x)=>x+100\nexport {other}f(float x)=>x+1\nexport g(int x)=>f(x)"
    c, _ = compile_linked(
        script("plot(lib.f(2))\nplot(lib.g(2))", version=version),
        {"user/Lib/1": library(decl, version=version)},
    )
    rt, cls = runtime_for(c)
    assert advance(rt, cls, [1, 2]) == [3.0, 102] * 2


@pytest.mark.parametrize("version", [5, 6])
def test_namespaces_with_separate_function_and_method_do_not_compete(version):
    libs = {
        "u/A/1": library("export f(string x)=>str.length(x)", "A", version),
        "u/B/1": library("export method f(int self)=>self+10", "B", version),
    }
    c, _ = compile_linked(
        script(
            'plot(a.f("abc"))\nplot(b.f(2))',
            imports="import u/A/1 as a\nimport u/B/1 as b",
            version=version,
        ),
        libs,
    )
    rt, cls = runtime_for(c)
    assert advance(rt, cls, [1, 2]) == [3, 12] * 2


@pytest.mark.parametrize("version", [5, 6])
def test_transitive_mixed_exports_remain_private_to_direct_import_scope(version):
    from pine2ast.libraries import LibraryError

    libs = {
        "u/Dep/1": library(
            "export f(string x)=>str.length(x)\nexport method f(int self)=>self+1", "Dep", version
        ),
        "user/Lib/1": library(
            "import u/Dep/1 as dep\nexport g(int x)=>dep.f(x)\nexport g(string x)=>dep.f(x)",
            version=version,
        ),
    }
    c, _ = compile_linked(script('plot(lib.g(2))\nplot(lib.g("abcd"))', version=version), libs)
    rt, cls = runtime_for(c)
    assert advance(rt, cls, [1]) == [3, 4]
    for bad in ["plot(lib.f(2))", "x=2\nplot(x.f())", "plot(dep.f(2))"]:
        with pytest.raises((LibraryError, ValueError)):
            compile_linked(script(bad, version=version), libs)


@pytest.mark.parametrize("version", [5, 6])
@pytest.mark.parametrize("imported", [False, True])
def test_sma_parameter_context_history_and_inputs_do_not_mix(version, imported):
    ns = "lib." if imported else ""
    decl = "export f(string x)=>str.length(x)\nexport method f(float self,simple int n)=>ta.sma(self,n)"
    c = compile_family(
        decl, f'n=input.int(2)\nplot({ns}f(close,n))\nplot({ns}f("abc"))', version, imported
    )
    for length in (2, 3):
        rt, cls = runtime_for(c, {"n": length})
        out = advance(rt, cls, [1, 2, 3])
        assert out[1::2] == [3] * 3
        assert all(is_na(x) for x in out[0 : 2 * (length - 1) : 2])
        assert out[2 * (length - 1) :: 2] == ([1.5, 2.5] if length == 2 else [2])
