# Generated by AST2Python
# Pine runtime contract: 1.4
# Source: current_basic_indicator.pine

from __future__ import annotations

from ast2python.errors import RuntimeContractError
from ast2python.runtime_contract.generated_base import GeneratedIndicatorBase
from pinelib.core import PineRuntime, na, pine_bool

REQUIRED_RUNTIME_CONTRACT = "1.4"

class GeneratedIndicator(GeneratedIndicatorBase):
    """
    Generated from Pine declaration: My Indicator
    """

    def __init__(self, params=None, runtime=None):
        self.params = params or {}
        self.rt = runtime
        if self.rt is None:
            raise RuntimeContractError("runtime is required for generated modules")
        if getattr(self.rt, 'contract_version', None) != REQUIRED_RUNTIME_CONTRACT:
            raise RuntimeContractError(f"P2A_CONTRACT_VERSION_MISMATCH: requires runtime contract {REQUIRED_RUNTIME_CONTRACT}, got {getattr(self.rt, 'contract_version', None)}")
        self.ctx = None
        self._var_initialized = {}
        self._init_series()
        self._init_inputs()

    def _init_series(self):
        pass

    def _init_inputs(self):
        pass

    # no user functions

    def run(self, bars):
        results = []
        for bar in bars:
            self.rt.begin_bar(bar)
            self._process_bar(bar)
            results.append(self._snapshot())
        return results

    def _snapshot(self):
        return {
            'bar_index': getattr(self.rt, 'bar_index', None),
        }

    def _process_bar(self, bar):
        # pine:L3
        self.rt.visual.plot(self.rt.close, source_map="L3")
