from __future__ import annotations

from ast2python.translator_parts.shared import *  # noqa: F403,F401


class TranslatorModuleMixin(TranslatorMixinBase):
    def _emit_module(
        self, program: ASTProgram, declaration: ASTNode, *, title: str, module_name: str
    ) -> None:
        self._collect_globals(program)
        self._declare_base_imports()
        self._declare_dynamic_imports(program)
        self.emitter.line("# Generated by AST2Python")
        self.emitter.line(f"# Pine runtime contract: {RUNTIME_CONTRACT_VERSION}")
        self.emitter.line(f"# Source: {module_name}.pine")
        self.emitter.line()
        self.emitter.line("from __future__ import annotations")
        self.emitter.line()
        for line in self.ctx.imports.render():
            self.emitter.line(line)
        self.emitter.line()
        self.emitter.line(f'REQUIRED_RUNTIME_CONTRACT = "{RUNTIME_CONTRACT_VERSION}"')
        self.emitter.line()
        self._emit_type_declarations(program)
        class_name = class_name_for_mode(self.ctx.mode)
        base_class = base_class_for_mode(self.ctx.mode)
        self.emitter.line(f"class {class_name}({base_class}):")
        self.emitter.indent()
        self.emitter.line('"""')
        self.emitter.line(f"Generated from Pine declaration: {title}")
        self.emitter.line('"""')
        self.emitter.line()
        self._emit_init(declaration)
        self.emitter.line()
        self._emit_function_declarations(program)
        self.emitter.line()
        self._emit_run()
        self.emitter.line()
        self._emit_snapshot()
        if self.ctx.mode != "library":
            self.emitter.line()
            self._emit_process_bar(program)
            # Emit _init_series after processing bar so global_series is complete
            self.emitter.line()
            self.emitter.line("def _init_series(self):")
            self.emitter.indent()
            if not self.global_series:
                self.emitter.line("pass")
            for info, dtype in self.global_series:
                self.emitter.line(
                    f'self.{info.py_name} = self.rt.series("{info.py_name}", dtype="{dtype}")'
                )
                self.emitter.line(f'self._var_initialized["{info.py_name}"] = False')
            self.emitter.dedent()
            self.emitter.line()
        self.emitter.dedent()

    def _declare_base_imports(self) -> None:
        self.ctx.imports.require_from("ast2python.errors", "RuntimeContractError")
        self.ctx.imports.require_from(
            "ast2python.runtime_contract.generated_base", base_class_for_mode(self.ctx.mode)
        )
        self.ctx.imports.require_from("pinelib.core", "PineRuntime")
        self.ctx.imports.require_from("pinelib.core", "na")
        self.ctx.imports.require_from("pinelib.core", "is_na")
        self.ctx.imports.require_from("pinelib.core", "pine_bool")
        for name in (
            "pine_add",
            "pine_sub",
            "pine_mul",
            "pine_div",
            "pine_eq",
            "pine_ne",
            "pine_gt",
            "pine_gte",
            "pine_lt",
            "pine_lte",
            "pine_int",
            "pine_float",
            "pine_str",
        ):
            self.ctx.imports.require_from("pinelib.core", name)
        self.ctx.imports.require_from("pinelib.request", "security", alias="request_security")
        if self.ctx.mode == "strategy":
            self.ctx.imports.require_from("pinelib.strategy", "StrategyContext")
        self.ctx.imports.require_from("pinelib.errors", "PineRuntimeError")
        self.ctx.imports.require_from("pinelib.errors", "PL_INPUT_VALIDATION_ERROR")

    def _declare_dynamic_imports(self, program: ASTProgram) -> None:
        """Predeclare imports needed by generated statements before rendering the header."""
        for node in program.descendants():
            if node.kind == "CallExpr":
                callee = node.child("callee")
                if callee is not None and member_chain(callee) == "request.security_lower_tf":
                    self.ctx.imports.require_from(
                        "pinelib.request", "security_lower_tf", alias="request_security_lower_tf"
                    )
                if callee is not None and member_chain(callee) == "request.footprint":
                    self.ctx.imports.require_from(
                        "pinelib.request", "footprint", alias="request_footprint"
                    )
            if node.kind in {"ForRangeStructure", "ForStructure"}:
                self.ctx.imports.require_from("pinelib.core", "pine_range")
            if node.kind == "ForInStructure":
                self.ctx.imports.require_from("builtins", "iter", alias="pine_iter")
            if node.kind in UDT_DECLARATIONS:
                self.ctx.imports.require_from("dataclasses", "dataclass")
            if node.kind in ENUM_DECLARATIONS:
                self.ctx.imports.require_from("enum", "Enum")
            if node.kind == "MemberAccessExpr":
                chain = member_chain(node)
                if chain is not None and chain.startswith("color."):
                    self.ctx.imports.require_from("pinelib", "color", alias="pine_color")
                if chain is not None and chain.startswith("ta."):
                    member = chain.split(".", 1)[1]
                    if member in DERIVED_BUILTIN_SERIES:
                        self.ctx.imports.require_from("pinelib.ta", f"{member}_series")
            # Scan for bare DERIVED_BUILTIN_SERIES identifiers (e.g., hlc3 in ta.cci(hlc3, 20))
            if node.kind == "Identifier":
                name = str(node.field("name"))
                if name in DERIVED_BUILTIN_SERIES:
                    self.ctx.imports.require_from("pinelib.ta", f"{name}_series")
            if node.kind != "CallExpr":
                continue
            callee = node.child("callee")
            chain = None if callee is None else member_chain(callee)
            if chain is None:
                continue
            if chain in {"na", "nz", "fixnan"}:
                self.ctx.imports.require_from("pinelib.core", "is_na" if chain == "na" else chain)
            if chain.startswith("ta."):
                member = chain.split(".", 1)[1]
                if member in DERIVED_BUILTIN_SERIES:
                    # ta.hl2, ta.hlc3, ta.ohlc4, ta.hlcc4 → need _series variant for rolling TA
                    self.ctx.imports.require_from("pinelib.ta", f"{member}_series")
                else:
                    sig = BUILTIN_SIGNATURES.get(chain)
                    if sig is not None:
                        fn = (
                            sig.builtin.split(".", 1)[1]
                            if sig.builtin.startswith("ta.")
                            else sig.builtin
                        )
                        self.ctx.imports.require_from("pinelib.ta", fn)
                    else:
                        self.ctx.imports.require_from("pinelib.ta", member)
            elif chain.startswith("math."):
                self.ctx.imports.require_from("pinelib.math", chain.split(".", 1)[1])
            elif chain.startswith("str."):
                self.ctx.imports.require_from("pinelib", "string", alias="pine_string")
            elif chain.startswith(("array.", "map.", "matrix.")):
                self.ctx.imports.require_from(
                    "pinelib.reference",
                    {"array": "PineArray", "map": "PineMap", "matrix": "PineMatrix"}[
                        chain.split(".", 1)[0]
                    ],
                )

    def _emit_init(self, declaration: ASTNode) -> None:
        self.emitter.line("def __init__(self, params=None, runtime=None):")
        self.emitter.indent()
        self.emitter.line("self.params = params or {}")
        self.emitter.line("self.rt = runtime")
        self.emitter.line("if self.rt is None:")
        self.emitter.indent()
        self.emitter.line('raise RuntimeContractError("runtime is required for generated modules")')
        self.emitter.dedent()
        self.emitter.line(
            "if getattr(self.rt, 'contract_version', None) != REQUIRED_RUNTIME_CONTRACT:"
        )
        self.emitter.indent()
        self.emitter.line(
            "raise RuntimeContractError("
            f'f"{CONTRACT_VERSION_MISMATCH}: requires runtime contract '
            "{REQUIRED_RUNTIME_CONTRACT}, got "
            "{getattr(self.rt, 'contract_version', None)}\""
            ")"
        )
        self.emitter.dedent()
        if self.ctx.mode == "strategy":
            self._emit_strategy_context(declaration)
            self.emitter.line("self.ctx.attach_runtime(self.rt)")
        else:
            self.emitter.line("self.ctx = None")
        self.emitter.line("self._var_initialized = {}")
        self.emitter.line("self.alerts = []")
        self.emitter.line("self.alert_conditions = []")
        self.emitter.line("self.external_library_calls = []")

        self.emitter.line("self._init_inputs()")
        self.emitter.dedent()
        self.emitter.line()
        self.emitter.line("def _record_alert(self, kind, *args, source_map=None, **kwargs):")
        self.emitter.indent()
        self.emitter.line(
            "payload = {'kind': kind, 'args': args, 'kwargs': kwargs, 'source_map': source_map}"
        )
        self.emitter.line(
            "(self.alert_conditions if kind == 'alertcondition' else self.alerts).append(payload)"
        )
        self.emitter.line("return None")
        self.emitter.dedent()
        self.emitter.line()
        self.emitter.line(
            "def _external_library_call(self, alias, member, *args, source_map=None, **kwargs):"
        )
        self.emitter.indent()
        self.emitter.line(
            "self.external_library_calls.append({'alias': alias, 'member': member, 'args': args, 'kwargs': kwargs, 'source_map': source_map})"  # noqa: E501
        )
        self.emitter.line("return na")
        self.emitter.dedent()
        self.emitter.line()
        self.emitter.line("def _visual_call(self, name, *args, source_map=None, **kwargs):")
        self.emitter.indent()
        self.emitter.line(
            "self.rt.plot_recorder.record(bar_time=self.rt.current_bar.time if self.rt.current_bar else 0, bar_index=self.rt.bar_index, name=name, value=args[0] if args else None, title=args[1] if len(args) > 1 else kwargs.get('title', ''), kwargs=kwargs)"  # noqa: E501
        )
        self.emitter.line("if name.endswith('.new'):")
        self.emitter.indent()
        self.emitter.line("kind = name.split('.', 1)[0]")
        self.emitter.line(
            "positional = {'line': ('x1', 'y1', 'x2', 'y2'), 'label': ('x', 'y', 'text'), 'box': ('left', 'top', 'right', 'bottom'), 'table': ('position', 'columns', 'rows')}.get(kind, ())"  # noqa: E501
        )
        self.emitter.line("attrs = dict(kwargs)")
        self.emitter.line("attrs.update({key: value for key, value in zip(positional, args)})")
        self.emitter.line("return self.rt.visual.new(kind, **attrs)")
        self.emitter.dedent()
        self.emitter.line("if name.split('.', 1)[0] in {'line', 'label', 'box', 'table'} and args:")
        self.emitter.indent()
        self.emitter.line("kind, method = name.split('.', 1)")
        self.emitter.line("if method == 'delete':")
        self.emitter.indent()
        self.emitter.line("return self.rt.visual.delete(args[0])")
        self.emitter.dedent()
        self.emitter.line("attrs = dict(kwargs)")
        self.emitter.line("attrs['_method'] = method")
        self.emitter.line("attrs['_args'] = args[1:]")
        self.emitter.line("return self.rt.visual.set(args[0], **attrs)")
        self.emitter.dedent()
        self.emitter.line("return None")
        self.emitter.dedent()
        self.emitter.line()
        self.emitter.line("def _init_inputs(self):")
        self.emitter.indent()
        if not self.input_series:
            self.emitter.line("pass")
        for info, dtype, meta in self.input_series:
            default = meta["default_python"]
            schema = repr(meta["public"])
            self.emitter.line(
                f'self.{info.py_name} = self.rt.series("{info.py_name}", dtype="{dtype}")'
            )
            # For source inputs, bind directly to the Series reference instead of using
            # set_current with a scalar. This avoids the na-at-init problem because
            # the Series reference itself (not its current value) is used.
            if dtype == "source":
                # Detect derived builtin series (hl2, hlc3, ohlc4, hlcc4) by their
                # characteristic scalar expansion patterns (pine_add of rt.*.current).
                # We check for the pattern where high.current, low.current, close.current
                # appear together, indicating hlc3 or similar.
                if isinstance(default, str) and "pine_add" in default and "rt." in default:
                    # Check which derived builtin: hlc3 has high+low+close, hl2 has high+low only
                    has_high = "rt.high" in default or "rt.high.current" in default
                    has_low = "rt.low" in default or "rt.low.current" in default
                    has_close = "rt.close" in default or "rt.close.current" in default
                    has_open = "rt.open" in default or "rt.open.current" in default
                    if has_high and has_low and has_close and has_open:
                        series_expr = "ohlc4_series(self.rt)"
                    elif has_high and has_low and has_close:
                        series_expr = "hlc3_series(self.rt)"
                    elif has_high and has_low:
                        series_expr = "hl2_series(self.rt)"
                    elif has_high and has_close:
                        series_expr = "hlcc4_series(self.rt)"
                    else:
                        series_expr = None
                    if series_expr:
                        self.emitter.line(f"self.{info.py_name} = {series_expr}")
                    else:
                        # Fallback: strip .current and hope for the best
                        source_ref = (
                            default.replace(".current", "") if isinstance(default, str) else default
                        )
                        self.emitter.line(f"self.{info.py_name} = {source_ref}")
                elif isinstance(default, str) and ".current" in default:
                    # Simple case: self.rt.close.current -> self.rt.close
                    source_ref = default.replace(".current", "")
                    self.emitter.line(f"self.{info.py_name} = {source_ref}")
                else:
                    self.emitter.line(f"self.{info.py_name} = {default}")
            else:
                self.emitter.line(
                    f'self.{info.py_name}.set_current(self._input_value("{info.pine_name}", {default}, {schema}))'  # noqa: E501
                )
        self.emitter.dedent()
        self.emitter.line()
        self.emitter.line("def _input_value(self, name, default, schema):")
        self.emitter.indent()
        self.emitter.line("value = self.params.get(name, default)")
        self.emitter.line("kind = schema.get('type')")
        self.emitter.line("def fail(message):")
        self.emitter.indent()
        self.emitter.line(
            "diagnostics = getattr(getattr(self.rt, 'config', None), 'diagnostics', None)"
        )
        self.emitter.line("if isinstance(diagnostics, list):")
        self.emitter.indent()
        self.emitter.line(
            "diagnostics.append({'code': PL_INPUT_VALIDATION_ERROR, 'message': message, 'input': name})"  # noqa: E501
        )
        self.emitter.dedent()
        self.emitter.line("raise PineRuntimeError(message, code=PL_INPUT_VALIDATION_ERROR)")
        self.emitter.dedent()
        self.emitter.line(
            "if kind == 'int' and (not isinstance(value, int) or isinstance(value, bool)):"
        )
        self.emitter.indent()
        self.emitter.line("fail(f'Input {name} must be int')")
        self.emitter.dedent()
        self.emitter.line(
            "if kind == 'float' and (not isinstance(value, (int, float)) or isinstance(value, bool)):"  # noqa: E501
        )
        self.emitter.indent()
        self.emitter.line("fail(f'Input {name} must be float')")
        self.emitter.dedent()
        self.emitter.line("if kind == 'bool' and not isinstance(value, bool):")
        self.emitter.indent()
        self.emitter.line("fail(f'Input {name} must be bool')")
        self.emitter.dedent()
        self.emitter.line(
            "if kind in {'string', 'session', 'timeframe'} and not isinstance(value, str):"
        )
        self.emitter.indent()
        self.emitter.line("fail(f'Input {name} must be string')")
        self.emitter.dedent()
        self.emitter.line("options = schema.get('options')")
        self.emitter.line("if options is not None and value not in options:")
        self.emitter.indent()
        self.emitter.line("fail(f'Input {name} must be one of {options!r}')")
        self.emitter.dedent()
        self.emitter.line("minval = schema.get('minval')")
        self.emitter.line("if minval is not None and value < minval:")
        self.emitter.indent()
        self.emitter.line("fail(f'Input {name} must be >= {minval!r}')")
        self.emitter.dedent()
        self.emitter.line("maxval = schema.get('maxval')")
        self.emitter.line("if maxval is not None and value > maxval:")
        self.emitter.indent()
        self.emitter.line("fail(f'Input {name} must be <= {maxval!r}')")
        self.emitter.dedent()
        self.emitter.line("return value")
        self.emitter.dedent()

    def _emit_strategy_context(self, declaration: ASTNode) -> None:
        kwargs = self._strategy_context_kwargs(declaration)
        if kwargs:
            self.emitter.line("self.ctx = StrategyContext(")
            self.emitter.indent()
            for key, value in kwargs:
                self.emitter.line(f"{key}={value},")
            self.emitter.dedent()
            self.emitter.line(")")
        else:
            self.emitter.line("self.ctx = StrategyContext()")

    def _emit_run(self) -> None:
        if self.ctx.mode == "strategy":
            self.emitter.line("def on_bar(self, runtime, strategy):")
            self.emitter.indent()
            self.emitter.line("bar = runtime.current_bar")
            self.emitter.line("if bar is None:")
            self.emitter.indent()
            self.emitter.line(
                'raise RuntimeContractError("strategy callback requires an active bar")'
            )
            self.emitter.dedent()
            self.emitter.line("self._process_bar(bar)")
            self.emitter.dedent()
            self.emitter.line()
            self.emitter.line("def run(self, bars):")
            self.emitter.indent()
            self.emitter.line("results = []")
            self.emitter.line("for bar in bars:")
            self.emitter.indent()
            self.emitter.line("self.rt.begin_bar(bar)")
            self.emitter.line("try:")
            self.emitter.indent()
            self.emitter.line("self._process_bar(bar)")
            self.emitter.dedent()
            self.emitter.line("finally:")
            self.emitter.indent()
            self.emitter.line("self.rt.end_bar()")
            self.emitter.dedent()
            self.emitter.line("results.append(self._snapshot())")
            self.emitter.dedent()
            self.emitter.line("return results")
            self.emitter.dedent()
            return
        self.emitter.line("def run(self, bars):")
        self.emitter.indent()
        self.emitter.line("results = []")
        self.emitter.line("for bar in bars:")
        self.emitter.indent()
        self.emitter.line("self.rt.begin_bar(bar)")
        self.emitter.line("try:")
        self.emitter.indent()
        if self.ctx.mode == "library":
            self.emitter.line("pass")
        else:
            self.emitter.line("self._process_bar(bar)")
        self.emitter.dedent()
        self.emitter.line("finally:")
        self.emitter.indent()
        self.emitter.line("self.rt.end_bar()")
        self.emitter.dedent()
        if self.ctx.mode == "library":
            self.emitter.line("results.append(None)")
        else:
            self.emitter.line("results.append(self._snapshot())")
        self.emitter.dedent()
        self.emitter.line("return results")
        self.emitter.dedent()

    def _emit_snapshot(self) -> None:
        self.emitter.line("def _snapshot(self):")
        self.emitter.indent()
        self.emitter.line("return {")
        self.emitter.indent()
        self.emitter.line("'bar_index': getattr(self.rt, 'bar_index', None),")
        if self.ctx.mode == "strategy":
            self.emitter.line("'pending_orders': len(getattr(self.ctx, 'pending_orders', ())),")
        self.emitter.dedent()
        self.emitter.line("}")
        self.emitter.dedent()

    def _emit_process_bar(self, program: ASTProgram) -> None:
        self.emitter.line("def _process_bar(self, bar):")
        self.emitter.indent()
        # Call _init_series on first bar so global_series is complete
        self.emitter.line("if not getattr(self, '_series_initialized', False):")
        self.emitter.indent()
        self.emitter.line("self._init_series()")
        self.emitter.line("self._series_initialized = True")
        self.emitter.dedent()
        if not program.items:
            self.emitter.line("pass")
        for item in program.items:
            if (
                item.kind
                in FUNCTION_DECLARATIONS
                | METHOD_DECLARATIONS
                | UDT_DECLARATIONS
                | ENUM_DECLARATIONS
                or item.kind == "ImportDeclaration"
            ):
                continue
            self._emit_statement(item)
        self.emitter.dedent()
