from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

ARRAY_SIGNATURES: dict[str, SignatureSpec] = {
    'array.avg': SignatureSpec(builtin='array.avg', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.copy': SignatureSpec(builtin='array.copy', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.from': SignatureSpec(builtin='array.from', parameters=(), min_varargs=0, vararg=ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.get': SignatureSpec(builtin='array.get', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='index', accepted_types=frozenset({'int'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.max': SignatureSpec(builtin='array.max', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.min': SignatureSpec(builtin='array.min', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.new': SignatureSpec(builtin='array.new', parameters=(ParameterSpec(name='initial_value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.new_bool': SignatureSpec(builtin='array.new_bool', parameters=(ParameterSpec(name='initial', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False), ParameterSpec(name='max_size', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.new_color': SignatureSpec(builtin='array.new_color', parameters=(ParameterSpec(name='initial', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False), ParameterSpec(name='max_size', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.new_float': SignatureSpec(builtin='array.new_float', parameters=(ParameterSpec(name='initial', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False), ParameterSpec(name='max_size', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.new_int': SignatureSpec(builtin='array.new_int', parameters=(ParameterSpec(name='initial', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False), ParameterSpec(name='max_size', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.new_string': SignatureSpec(builtin='array.new_string', parameters=(ParameterSpec(name='initial', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False), ParameterSpec(name='max_size', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.push': SignatureSpec(builtin='array.push', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.set': SignatureSpec(builtin='array.set', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='index', accepted_types=frozenset({'int'}), qualifier_max='series', required=True), ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.shift': SignatureSpec(builtin='array.shift', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='index', accepted_types=frozenset({'int'}), qualifier_max='series', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.size': SignatureSpec(builtin='array.size', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.sort': SignatureSpec(builtin='array.sort', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='order', accepted_types=frozenset({'string'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'array.sum': SignatureSpec(builtin='array.sum', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
}
