from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

BOX_SIGNATURES: dict[str, SignatureSpec] = {
    'box.delete': SignatureSpec(builtin='box.delete', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineObjectId', 'line', 'table', 'box', 'label'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'box.new': SignatureSpec(builtin='box.new', parameters=(ParameterSpec(name='left', accepted_types=frozenset({'int'}), qualifier_max='series', required=True), ParameterSpec(name='top', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True), ParameterSpec(name='right', accepted_types=frozenset({'int'}), qualifier_max='series', required=True), ParameterSpec(name='bottom', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset({'border_style', 'extend', 'text_size', 'bgcolor', 'xloc', 'text_valign', 'text_color', 'border_color', 'text', 'border_width', 'text_halign', 'force_overlay'}), codegen_supported=True, notes=''),
    'box.set_bottom': SignatureSpec(builtin='box.set_bottom', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineObjectId', 'line', 'table', 'box', 'label'}), qualifier_max='series', required=True), ParameterSpec(name='bottom', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'box.set_left': SignatureSpec(builtin='box.set_left', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineObjectId', 'line', 'table', 'box', 'label'}), qualifier_max='series', required=True), ParameterSpec(name='left', accepted_types=frozenset({'int'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'box.set_right': SignatureSpec(builtin='box.set_right', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineObjectId', 'line', 'table', 'box', 'label'}), qualifier_max='series', required=True), ParameterSpec(name='right', accepted_types=frozenset({'int'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'box.set_top': SignatureSpec(builtin='box.set_top', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineObjectId', 'line', 'table', 'box', 'label'}), qualifier_max='series', required=True), ParameterSpec(name='top', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
}
