from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

MAP_SIGNATURES: dict[str, SignatureSpec] = {
    'map.contains': SignatureSpec(builtin='map.contains', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='key', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'map.copy': SignatureSpec(builtin='map.copy', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'map.get': SignatureSpec(builtin='map.get', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='key', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='default', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'map.new': SignatureSpec(builtin='map.new', parameters=(), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'map.put': SignatureSpec(builtin='map.put', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='key', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'map.remove': SignatureSpec(builtin='map.remove', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='key', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'map.size': SignatureSpec(builtin='map.size', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
}
