from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

MATH_SIGNATURES: dict[str, SignatureSpec] = {
    'math.abs': SignatureSpec(builtin='math.abs', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.acos': SignatureSpec(builtin='math.acos', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.asin': SignatureSpec(builtin='math.asin', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.atan': SignatureSpec(builtin='math.atan', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.avg': SignatureSpec(builtin='math.avg', parameters=(), min_varargs=1, vararg=ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True), allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.ceil': SignatureSpec(builtin='math.ceil', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.cos': SignatureSpec(builtin='math.cos', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.exp': SignatureSpec(builtin='math.exp', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.floor': SignatureSpec(builtin='math.floor', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.log': SignatureSpec(builtin='math.log', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.log10': SignatureSpec(builtin='math.log10', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.max': SignatureSpec(builtin='math.max', parameters=(), min_varargs=1, vararg=ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True), allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.min': SignatureSpec(builtin='math.min', parameters=(), min_varargs=1, vararg=ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True), allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.pow': SignatureSpec(builtin='math.pow', parameters=(ParameterSpec(name='base', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True), ParameterSpec(name='exponent', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.random': SignatureSpec(builtin='math.random', parameters=(ParameterSpec(name='min', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='simple', required=False), ParameterSpec(name='max', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='simple', required=False), ParameterSpec(name='seed', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.round': SignatureSpec(builtin='math.round', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True), ParameterSpec(name='precision', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.sign': SignatureSpec(builtin='math.sign', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.sin': SignatureSpec(builtin='math.sin', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.sqrt': SignatureSpec(builtin='math.sqrt', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.tan': SignatureSpec(builtin='math.tan', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.todegrees': SignatureSpec(builtin='math.todegrees', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.toradians': SignatureSpec(builtin='math.toradians', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'math.trunc': SignatureSpec(builtin='math.trunc', parameters=(ParameterSpec(name='number', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
}
