from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

MATRIX_SIGNATURES: dict[str, SignatureSpec] = {
    'matrix.cols': SignatureSpec(builtin='matrix.cols', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'matrix.columns': SignatureSpec(builtin='matrix.columns', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'matrix.copy': SignatureSpec(builtin='matrix.copy', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'matrix.get': SignatureSpec(builtin='matrix.get', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='row', accepted_types=frozenset({'int'}), qualifier_max='series', required=True), ParameterSpec(name='column', accepted_types=frozenset({'int'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'matrix.new': SignatureSpec(builtin='matrix.new', parameters=(ParameterSpec(name='rows', accepted_types=frozenset({'int'}), qualifier_max='simple', required=True), ParameterSpec(name='columns', accepted_types=frozenset({'int'}), qualifier_max='simple', required=True), ParameterSpec(name='initial_value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'matrix.rows': SignatureSpec(builtin='matrix.rows', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'matrix.set': SignatureSpec(builtin='matrix.set', parameters=(ParameterSpec(name='id', accepted_types=frozenset({'PineArray', 'PineMatrix', 'array', 'PineMap', 'map', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='row', accepted_types=frozenset({'int'}), qualifier_max='series', required=True), ParameterSpec(name='column', accepted_types=frozenset({'int'}), qualifier_max='series', required=True), ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
}
