from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

MISC_SIGNATURES: dict[str, SignatureSpec] = {
    'barcolor': SignatureSpec(builtin='barcolor', parameters=(ParameterSpec(name='color', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset({'title', 'offset', 'display', 'show_last', 'editable'}), codegen_supported=True, notes=''),
    'bgcolor': SignatureSpec(builtin='bgcolor', parameters=(ParameterSpec(name='color', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset({'title', 'offset', 'display', 'show_last', 'editable'}), codegen_supported=True, notes=''),
    'bool': SignatureSpec(builtin='bool', parameters=(ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'fill': SignatureSpec(builtin='fill', parameters=(ParameterSpec(name='hline1', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='hline2', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset({'title', 'color', 'fillgaps', 'display', 'editable'}), codegen_supported=True, notes=''),
    'float': SignatureSpec(builtin='float', parameters=(ParameterSpec(name='value', accepted_types=frozenset({'int', 'float', 'bool', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'hline': SignatureSpec(builtin='hline', parameters=(ParameterSpec(name='price', accepted_types=frozenset({'int', 'float', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset({'title', 'color', 'linestyle', 'display', 'linewidth', 'editable'}), codegen_supported=True, notes=''),
    'int': SignatureSpec(builtin='int', parameters=(ParameterSpec(name='value', accepted_types=frozenset({'int', 'float', 'bool', 'source'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'plot': SignatureSpec(builtin='plot', parameters=(ParameterSpec(name='series', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='title', accepted_types=frozenset({'string'}), qualifier_max='simple', required=False), ParameterSpec(name='color', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset({'join', 'precision', 'style', 'display', 'show_last', 'force_overlay', 'trackprice', 'offset', 'editable', 'linewidth', 'format', 'histbase'}), codegen_supported=True, notes=''),
    'plotchar': SignatureSpec(builtin='plotchar', parameters=(ParameterSpec(name='series', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset({'title', 'color', 'textcolor', 'display', 'show_last', 'offset', 'size', 'char', 'text', 'location'}), codegen_supported=True, notes=''),
    'plotshape': SignatureSpec(builtin='plotshape', parameters=(ParameterSpec(name='series', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset({'title', 'color', 'style', 'display', 'show_last', 'textcolor', 'offset', 'size', 'text', 'location'}), codegen_supported=True, notes=''),
    'str': SignatureSpec(builtin='str', parameters=(ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'strategy': SignatureSpec(builtin='strategy', parameters=(), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
}
