from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

REQUEST_SIGNATURES: dict[str, SignatureSpec] = {
    'request.footprint': SignatureSpec(builtin='request.footprint', parameters=(ParameterSpec(name='ticks_per_row', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False), ParameterSpec(name='value_area', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False), ParameterSpec(name='imbalance', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes='unsupported by PineLib data runtime; lowered through request stub policy'),
    'request.security': SignatureSpec(builtin='request.security', parameters=(ParameterSpec(name='symbol', accepted_types=frozenset({'object', 'string'}), qualifier_max='series', required=True), ParameterSpec(name='timeframe', accepted_types=frozenset({'object', 'string'}), qualifier_max='series', required=True), ParameterSpec(name='expression', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='gaps', accepted_types=frozenset({'string'}), qualifier_max='simple', required=False), ParameterSpec(name='lookahead', accepted_types=frozenset({'string'}), qualifier_max='simple', required=False), ParameterSpec(name='ignore_invalid_symbol', accepted_types=frozenset({'bool'}), qualifier_max='simple', required=False), ParameterSpec(name='currency', accepted_types=frozenset({'string'}), qualifier_max='simple', required=False), ParameterSpec(name='calc_bars_count', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'request.security_lower_tf': SignatureSpec(builtin='request.security_lower_tf', parameters=(ParameterSpec(name='symbol', accepted_types=frozenset({'object', 'string'}), qualifier_max='series', required=True), ParameterSpec(name='timeframe', accepted_types=frozenset({'object', 'string'}), qualifier_max='series', required=True), ParameterSpec(name='expression', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='ignore_invalid_symbol', accepted_types=frozenset({'bool'}), qualifier_max='simple', required=False), ParameterSpec(name='ignore_invalid_timeframe', accepted_types=frozenset({'bool'}), qualifier_max='simple', required=False), ParameterSpec(name='currency', accepted_types=frozenset({'string'}), qualifier_max='simple', required=False), ParameterSpec(name='calc_bars_count', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes='PineLib runtime_contract_v1.4 bounded lower-timeframe array slice'),
}
