from __future__ import annotations

# Generated signature registry; keep compact for architecture-budget readability.
# fmt: off
from ast2python.binder_model import ParameterSpec, SignatureSpec

STR_SIGNATURES: dict[str, SignatureSpec] = {
    'str.contains': SignatureSpec(builtin='str.contains', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='str', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.endswith': SignatureSpec(builtin='str.endswith', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='str', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.format': SignatureSpec(builtin='str.format', parameters=(ParameterSpec(name='format', accepted_types=frozenset({'string'}), qualifier_max='simple', required=True), ParameterSpec(name='arg1', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.length': SignatureSpec(builtin='str.length', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.lower': SignatureSpec(builtin='str.lower', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.pos': SignatureSpec(builtin='str.pos', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='str', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.replace': SignatureSpec(builtin='str.replace', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='target', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='simple', required=True), ParameterSpec(name='replacement', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='simple', required=True), ParameterSpec(name='occurrence', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.startswith': SignatureSpec(builtin='str.startswith', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='str', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.substring': SignatureSpec(builtin='str.substring', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='begin_pos', accepted_types=frozenset({'int'}), qualifier_max='simple', required=True), ParameterSpec(name='end_pos', accepted_types=frozenset({'int'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.tonumber': SignatureSpec(builtin='str.tonumber', parameters=(ParameterSpec(name='string', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.tostring': SignatureSpec(builtin='str.tostring', parameters=(ParameterSpec(name='value', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True), ParameterSpec(name='format', accepted_types=frozenset({'string'}), qualifier_max='simple', required=False)), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
    'str.upper': SignatureSpec(builtin='str.upper', parameters=(ParameterSpec(name='source', accepted_types=frozenset({'color', 'object', 'array', 'map', 'bool', 'any', 'string', 'int', 'float', 'PineObjectId', 'matrix'}), qualifier_max='series', required=True),), min_varargs=0, vararg=None, allow_extra_named=frozenset(), codegen_supported=True, notes=''),
}
